### ISSUE TITLE
Showcase Example

### ISSUE THREAD

**Issue by netzdoktor** [RalfJung/cargo-careful#10]
Thanks for this interesting tool. It would be great to have a short (realistic) piece of code in the README on which `careful` would trigger.

Is there some?

**Comment by RalfJung** [comment]
Do you want short or realistic? ;) Actually real examples are not going to be short...

**Comment by netzdoktor** [comment]
Right, that's a bit underspecified ;-)

Short: not a full-blown crate with various files that must be understood. Ideally, a single .rs file that is not 1000s of lines.

Realistic: well a simple, but an unrealistic example would be to use an `_unchecked` method and throw in nonsense. You also mention *nightly-only* checks in the README. Maybe such a check could be shown in action?

**Comment by netzdoktor** [comment]
I was referring to this:

https://github.com/RalfJung/cargo-careful/blob/master/README.md?plain=1#L30

**Comment by RalfJung** [comment]
Yes. That just means that cargo-careful won't work on stable Rust. And it says that explicitly:
> Running `cargo careful` requires a recent nightly toolchain.

I'm sorry I am not clear on what kind of example would actually be useful for users here...

**Comment by RalfJung** [comment]
I don't know how far layout randomization goes, maybe someone on Zulip knows.

**Comment by RalfJung** [comment]
> For teaching and simply motivating cargo careful, I'm now using this:

Thanks for the example! I have adjusted it a bit and added it to the readme.
