### ISSUE TITLE
Proposal: Enable main thread checking on Apple platforms

### ISSUE THREAD

**Issue by madsmtm** [RalfJung/cargo-careful#22]
On Apple platforms (macOS, iOS, tvOS and watchOS), basically all UI code is required to run on the main thread.

In Xcode 9.0 [Apple introduced the "Main Thread Checker"](https://developer.apple.com/library/archive/releasenotes/DeveloperTools/RN-Xcode/Chapters/Introduction.html#//apple_ref/doc/uid/TP40001051-CH1-SW974), which is a way for developers to enable extra assertions to ensure that their application conform to these requirements.

It is unclear whether doing work off the main thread is UB in the strictest sense or not (depends on how atomic AppKit/UIKit's internal structures are, which I've yet to find documentation about), but I think `cargo-careful` would be a good place to enable such a thing anyhow.

Xcode enables it by default, and [Apple's own documentation](https://developer.apple.com/documentation/xcode/diagnosing-memory-thread-and-crash-issues-early#Detect-improper-UI-updates-on-background-threads) reports a 1–2% CPU overhead, so I don't think there's anything to be worried about there. Also, if AppKit or UIKit is not loaded into the process, the checker simply does nothing.

Enabling it is as simple as inserting a dynamic library:
```console
DYLD_INSERT_LIBRARIES=/Applications/Xcode.app/Contents/Developer/usr/lib/libMainThreadChecker.dylib ./target/debug/my_binary
```

(Of course an actual implementation in `cargo-careful` should use the current Xcode version via. `xcode-select --print-path`, and with proper error handling for people who don't have Xcode installed / have a too old version of Xcode to include that `dylib`).

For prosperity, I'll link [this excellent blog post](https://bryce.co/main-thread-checker-configuration/) about the Main Thread Checker that outlines some undocumented options, if anyone's interested.

**Comment by RalfJung** [comment]
I've never used an Apple device in my life, so I can't really comment on this, but if someone can figure out a reliable way to implement this automatically (ideally something tested by our CI, maybe behind a flag), then sure, sounds useful.
