### ISSUE TITLE
Sysroot build fails on Nix shell

### ISSUE THREAD

**Issue by DieracDelta** [RalfJung/cargo-careful#3]
I'm trying to use this tool in a nix shell. For some reason, it's sticking it in a write only directory (`/tmp/nix-shell.NL1aJs/rustc-build-sysroot.6BErGTCriFwN`). Could the sysroot directory be made configurable via flag or environment variable? I'm happy to implement if you'll pull it in :)

**Comment by RalfJung** [comment]
That is the temporary directory used for building. The actual sysroot should be put into the XDG cache directory.

Are you saying your temp_dir does not work for writing and reading files? That sounds like a pretty broken configuration to me, not sure how anything would work with that?

**Comment by RalfJung** [comment]
If you are getting build errors, could you share the full output?

**Comment by RalfJung** [comment]
You should be able to set a different tempdir by setting the TMPDIR env var. But I am still curious why the default would not work for you.

**Comment by DieracDelta** [comment]
The full output:

```
$ cargo careful setup
Preparing a careful sysroot (target: x86_64-unknown-linux-gnu)...
error: failed to write /tmp/nix-shell.z96En4/rustc-build-sysroot.CJmRqR7HHqFF/Cargo.lock

Caused by:
  failed to open: /tmp/nix-shell.z96En4/rustc-build-sysroot.CJmRqR7HHqFF/Cargo.lock

Caused by:
  Permission denied (os error 13)
thread 'main' panicked at 'failed to build sysroot; run `cargo careful setup` to see what went wrong: sysroot build failed', src/main.rs:219:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by DieracDelta** [comment]
That's quite strange. For some reason cargo does not have write permissions to a directory that is allowed to be write for my user. Things work as root. Hmm.

**Comment by RalfJung** [comment]
So somehow TMPDIR is not writable on your system? Hm... no the folder must be writeable, since the writing that cargo-careful itself does (to construct a workspace for cargo) works fine. It's only when starting `cargo` to do the sysroot build that things go wrong.

Maybe it is some kind of process isolation thing, where when a process starts sub-processes, those don't have access to the same TMPDIR? But that also sounds like it could break many things; starting sub-processes is a standard idiom on Unix and should be supported even on NixOS. (Is this NixOS? Some Nix seems to be involved. Nix is known to overthrow fundamental Unix/POSIX assumptions but not being able to prepare files for a subprocess in TMPDIR is going a bit too far IMO.^^)

**Comment by DieracDelta** [comment]
I'm on a ubuntu machine with `nix` installed. So, not NixOS yet (though if I can get this to work I'm hoping to upstream!). I'm inside a `nix-shell` that has `cargo-useful` built and on my PATH. I've also got the `RUST_LIB_SRC` env var set correctly AFAICT. 

I tried setting TMPDIR to a directory in my `$HOME` and still end up with the same error. I need to investigate further, but perhaps it's something related to running the `execvp` syscall inside nix shells..

**Comment by RalfJung** [comment]
> I've also got the RUST_LIB_SRC env var set correctly AFAICT.

FWIW that shouldn't be needed, it will auto-detect the source folder of the active rustup toolchain. But also that can't really be the source of the problem anyway.

**Comment by RalfJung** [comment]
Hm... I had another idea for what this might be -- I distantly recall encountering something like that in the past, and then adding [code like this](https://github.com/japaric/xargo/blob/68e0ca57cd90837fe02f262f074182f9cfeb6227/src/sysroot.rs#L123) to xargo. The lockfile is created by copying it from the lib source dir, and if that is for some reason read-only then those permissions might be copied to the new location.

That still doesn't explain why so far nobody else seems to have seen this but it's more plausibvle than

**Comment by RalfJung** [comment]
@DieracDelta could you try the latest git version? It now explicitly disables "read-only" on the lockfile. which should hopefully fix your problem.
```
cargo install cargo-careful --git https://github.com/RalfJung/cargo-careful
```

**Comment by DieracDelta** [comment]
That fixed it!! Thank you for your help! I'm quite excited to be using this on my projects :)

Related: upstreaming [here](https://github.com/NixOS/nixpkgs/pull/193542)

**Comment by RalfJung** [comment]
Great, thanks for reporting and testing. I'll ship a new release then. :)
