### ISSUE TITLE
Please release a version with `rustc-build-sysroot` 0.5.3

### ISSUE THREAD

**Issue by davidhewitt** [RalfJung/cargo-careful#36]
I see in `rustc-build-sysroot` that the new location of `Cargo.lock` has been accounted for (see e.g. https://github.com/rust-lang/cargo/pull/14358), but it looks like we need an update here too?

Running `cargo careful setup` with `nightly-2024-08-08`, I get:

```
Preparing a careful sysroot (target: x86_64-unknown-linux-gnu)... 
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-careful-0.4.2/src/main.rs:267:10:
failed to build sysroot; run `cargo careful setup` to see what went wrong: failed to copy lockfile from sysroot source

Caused by:
    No such file or directory (os error 2)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by RalfJung** [comment]
Doing "cargo install -f" should pick up the updated depencency. But maybe I should do a new release nevertheless...

**Comment by davidhewitt** [comment]
We run `cargo careful` in PyO3 CI so would prefer to save the CI minutes and just install a prebuilt binary (though I did consider building with the updated dependency).

**Comment by RalfJung** [comment]
Ah right I entirely forgot about the prebuilt binaries^^

**Comment by RalfJung** [comment]
v0.4.3 is out now, the binaries are being built as we speak.

**Comment by davidhewitt** [comment]
Many thanks!
