### ISSUE TITLE
Feature request: Add a build command

### ISSUE THREAD

**Issue by jplatte** [RalfJung/cargo-careful#9]
Unless there is some reason it's not as easy as `run` / `test`?

**Comment by RalfJung** [comment]
It should be just as easy, I just lacked the creativity for what it could be useful for.^^

**Comment by jplatte** [comment]
We (matrix-org) have a use case in running the resulting library as part of a Swift package, in iOS simulator x)

A regular, "non-careful" debug build causes `EXC_BAD_ACCESS` and a debugger hasn't helped much in figuring out what's happening, so I was hoping a careful build could help.
